# Generated by Django 6.0.4 on 2026-05-03 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LineupImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='cs2pedia/lineups', verbose_name='Зображення')),
                ('img_mini', models.ImageField(blank=True, null=True, upload_to='cs2pedia/lineups/mini', verbose_name='Стиснуте зображення')),
                ('alt_text', models.CharField(blank=True, max_length=250, null=True, verbose_name='Підпис')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Зображення',
                'verbose_name_plural': 'Зображення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('meta', models.CharField(blank=True, max_length=250, null=True, verbose_name='Мета')),
                ('keywords', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ключові слова')),
                ('image', models.ImageField(upload_to='cs2pedia/maps/', verbose_name='Мапа')),
                ('photo_minified', models.ImageField(blank=True, null=True, upload_to='cs2pedia/maps/mini/', verbose_name='Стиснута мапа')),
                ('alt_text', models.CharField(blank=True, max_length=250, null=True, verbose_name='Підпис')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Кількість переглядів')),
                ('is_in_pool', models.BooleanField(default=True, verbose_name='В мап-пулі')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опублікувати')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Мапа',
                'verbose_name_plural': 'Мапи',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StratImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='cs2pedia/strategies', verbose_name='Зображення')),
                ('img_mini', models.ImageField(blank=True, null=True, upload_to='cs2pedia/strategies/mini', verbose_name='Стиснуте зображення')),
                ('alt_text', models.CharField(blank=True, max_length=250, null=True, verbose_name='Підпис')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Зображення',
                'verbose_name_plural': 'Зображення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис лайнапу')),
                ('comment', models.TextField(blank=True, verbose_name='Додатковий коментар')),
                ('throw_from', models.CharField(blank=True, max_length=100, verbose_name='Звідки')),
                ('land_at', models.CharField(blank=True, max_length=100, verbose_name='Куди')),
                ('video_url', models.URLField(blank=True, help_text='Посилання на відео завантажене кудись. Потім можемо домовитись про конкретну платформу або локальне зберігання.', verbose_name='Відео')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Кількість переглядів')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опублікувати')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Створено')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_lineups', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('slide', models.ManyToManyField(blank=True, to='cs2pedia.lineupimg', verbose_name='Зображення')),
                ('mapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_lineups', to='cs2pedia.map', verbose_name='Мапа')),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('side', models.CharField(choices=[('T', 'T'), ('CT', 'CT')], max_length=10, verbose_name='Сторона')),
                ('description', models.TextField(blank=True, verbose_name='Вміст')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Кількість переглядів')),
                ('is_active', models.BooleanField(default=True, verbose_name='В роботі')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Створено')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_strategies', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('mapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_strategies', to='cs2pedia.map', verbose_name='Мапа')),
                ('slide', models.ManyToManyField(blank=True, to='cs2pedia.stratimg', verbose_name='Зображення')),
            ],
            options={
                'verbose_name': 'Страта',
                'verbose_name_plural': 'Страти',
                'ordering': ['mapa', 'name'],
            },
        ),
    ]
