# Generated by Django 6.0.4 on 2026-05-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs2pedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineup',
            options={'ordering': ['mapa', 'title', '-likes'], 'verbose_name': 'Лайнап', 'verbose_name_plural': 'Лайнапи'},
        ),
        migrations.AlterModelOptions(
            name='strategy',
            options={'ordering': ['mapa', 'name', '-likes'], 'verbose_name': 'Страта', 'verbose_name_plural': 'Страти'},
        ),
        migrations.RemoveField(
            model_name='lineup',
            name='views',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='views',
        ),
        migrations.AddField(
            model_name='lineup',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Вподобання'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='utility',
            field=models.CharField(choices=[('smoke', 'Смок'), ('molotov', 'Молік'), ('flash', 'Флеш'), ('he', 'ХаЕ'), ('decoy', 'Декой')], default=1, max_length=10, verbose_name='Граната'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strategy',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Вподобання'),
        ),
        migrations.AlterField(
            model_name='lineup',
            name='description',
            field=models.CharField(blank=True, help_text='Наприклад: W + jumpthrow.', max_length=200, verbose_name='Опис лайнапу'),
        ),
    ]
