# Generated by Django 6.0.4 on 2026-05-03 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs2pedia', '0002_alter_lineup_options_alter_strategy_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='photo_minified',
            new_name='image_mini',
        ),
    ]
