# Generated by Django 6.0.4 on 2026-05-03 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs2pedia', '0003_rename_photo_minified_map_image_mini'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='image_mini',
            new_name='img_mini',
        ),
    ]
