# Generated by Django 6.0.4 on 2026-05-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs2pedia', '0004_rename_image_mini_map_img_mini'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='map',
            options={'ordering': ['-is_published', '-is_in_pool', 'name'], 'verbose_name': 'Мапа', 'verbose_name_plural': 'Мапи'},
        ),
        migrations.AddField(
            model_name='strategy',
            name='slug',
            field=models.SlugField(default='test', unique=True, verbose_name='Слаг'),
            preserve_default=False,
        ),
    ]
