# Generated by Django 6.0.4 on 2026-05-25 12:28

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs2pedia', '0005_alter_map_options_strategy_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Вміст'),
        ),
    ]
