# Generated by Django 6.0.4 on 2026-05-30 12:50

import cs2pedia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs2pedia', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineupimg',
            name='comment',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Підпис'),
        ),
        migrations.AddField(
            model_name='lineupimg',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='stratimg',
            name='comment',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Підпис'),
        ),
        migrations.AddField(
            model_name='stratimg',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='lineupimg',
            name='alt_text',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Альт атрибут'),
        ),
        migrations.AlterField(
            model_name='lineupimg',
            name='img',
            field=models.ImageField(upload_to=cs2pedia.models.ImageUploadTo('cs2pedia/lineups'), verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='lineupimg',
            name='img_mini',
            field=models.ImageField(blank=True, null=True, upload_to=cs2pedia.models.ImageUploadTo('cs2pedia/lineups/mini', suffix='_mini'), verbose_name='Стиснуте зображення'),
        ),
        migrations.AlterField(
            model_name='stratimg',
            name='alt_text',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Альт атрибут'),
        ),
        migrations.AlterField(
            model_name='stratimg',
            name='img',
            field=models.ImageField(upload_to=cs2pedia.models.ImageUploadTo('cs2pedia/strategies'), verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='stratimg',
            name='img_mini',
            field=models.ImageField(blank=True, null=True, upload_to=cs2pedia.models.ImageUploadTo('cs2pedia/strategies/mini', suffix='_mini'), verbose_name='Стиснуте зображення'),
        ),
    ]
