# Generated by Django 6.0.4 on 2026-06-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs2pedia', '0008_lineupimg_comment_lineupimg_name_stratimg_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='meta',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Мета'),
        ),
    ]
