"""
Django settings for pomichnyk_core project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

import environ
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

env = environ.Env()
environ.Env.read_env()

# Take environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
env = environ.Env(
	# set casting, default value
	DEBUG=(bool, True)
)
DEBUG = env('DEBUG')

ADMINS = [
    ("Yulian T", "yulian.tolkachov@gmail.com"),
]

BASE_DIR = Path(__file__).resolve().parent.parent

ALLOWED_HOSTS = [
	'127.0.0.1',
	'pomichnyk.yuliandev.space',
	'www.pomichnyk.yuliandev.space',
]


# Application definition

INSTALLED_APPS = [
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'cs2pedia.apps.Cs2PediaConfig',
	'django_ckeditor_5',
]

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pomichnyk_core.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [
			os.path.join(BASE_DIR, "templates"),
		],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

WSGI_APPLICATION = 'pomichnyk_core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.sqlite3',
		'NAME': BASE_DIR / 'db.sqlite3',
	}
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'uk'

LANGUAGES = (
	('en', 'English'),
	('uk', 'Ukrainian'),
)

TIME_ZONE = 'Europe/Kyiv'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
if DEBUG:
	STATIC_ROOT = os.path.join(BASE_DIR, "static")
else:
	STATIC_ROOT = "/home/h67964c/pomichnyk.yuliandev.space/static" # this server settings
STATICFILES_DIRS = [
	os.path.join(BASE_DIR, "staticfiles"),
]

MEDIA_URL = '/media/'
if DEBUG:
	MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
else:
	MEDIA_ROOT = "/home/h67964c/pomichnyk/media" # this server settings


LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "pomichnyk_core:creator_dashboard"
LOGOUT_REDIRECT_URL = "pomichnyk_core:index"


customColorPalette = [
	{
		'color': 'hsl(4, 90%, 58%)',
		'label': 'Red'
	},
	{
		'color': 'hsl(340, 82%, 52%)',
		'label': 'Pink'
	},
	{
		'color': 'hsl(291, 64%, 42%)',
		'label': 'Purple'
	},
	{
		'color': 'hsl(262, 52%, 47%)',
		'label': 'Deep Purple'
	},
	{
		'color': 'hsl(231, 48%, 48%)',
		'label': 'Indigo'
	},
	{
		'color': 'hsl(207, 90%, 54%)',
		'label': 'Blue'
	},
]

CKEDITOR_5_UPLOAD_FILE_TYPES = ['jpeg', 'png', 'jpg', 'gif']

CKEDITOR_5_CONFIGS = {
	'default': {
		'toolbar': {
			'items': ['heading', '|', 'bold', 'italic', 'link',
					  'bulletedList', 'numberedList', 'blockQuote', 'imageUpload', ],
					},
		'language': ['uk', 'en'],

	},
	'extends': {
		'blockToolbar': [
			'paragraph', 'heading1', 'heading2', 'heading3',
			'|',
			'bulletedList', 'numberedList',
			'|',
			'blockQuote',
		],
		'toolbar': {
			'items': ['heading', '|', 'outdent', 'indent', '|', 'bold', 'italic', 'link', 'underline', 'strikethrough',
					  'code','subscript', 'superscript', 'highlight', '|', 'codeBlock', 'sourceEditing', 'insertImage',
					'bulletedList', 'numberedList', 'todoList', '|',  'blockQuote', 'imageUpload', '|',
					'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', 'mediaEmbed', 'removeFormat',
					'insertTable',
					],
			'shouldNotGroupWhenFull': 'true'
		},
		'image': {
			'toolbar': ['imageTextAlternative', '|', 'imageStyle:alignLeft',
						'imageStyle:alignRight', 'imageStyle:alignCenter', 'imageStyle:side',  '|'],
			'styles': [
				'full',
				'side',
				'alignLeft',
				'alignRight',
				'alignCenter',
			]

		},
		'table': {
			'contentToolbar': [ 'tableColumn', 'tableRow', 'mergeTableCells',
			'tableProperties', 'tableCellProperties' ],
			'tableProperties': {
				'borderColors': customColorPalette,
				'backgroundColors': customColorPalette
			},
			'tableCellProperties': {
				'borderColors': customColorPalette,
				'backgroundColors': customColorPalette
			}
		},
		'heading' : {
			'options': [
				{ 'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph' },
				{ 'model': 'heading1', 'view': 'h1', 'title': 'Heading 1', 'class': 'ck-heading_heading1' },
				{ 'model': 'heading2', 'view': 'h2', 'title': 'Heading 2', 'class': 'ck-heading_heading2' },
				{ 'model': 'heading3', 'view': 'h3', 'title': 'Heading 3', 'class': 'ck-heading_heading3' }
			]
		}
	},
	'list': {
		'properties': {
			'styles': 'true',
			'startIndex': 'true',
			'reversed': 'true',
		}
	}
}

# Define a constant in settings.py to specify file upload permissions
CKEDITOR_5_FILE_UPLOAD_PERMISSION = "authenticated"  # Possible values: "staff", "authenticated", "any"